### ISSUE TITLE
How to reverse timeline ?

### ISSUE THREAD

**Issue by nitneuq33000** [softmarshmallow/flutter-timeline#12]
Hello I don't find how to display most recent event on top and last on bottom. 

thank you

**Comment by softmarshmallow** [comment]
You may want to sort your data yourself, And pass the data to the timeline.

```
var data = [.., .., .., ];
data.sort((a, b) => a.time.compare(b.time))
```

https://api.dart.dev/stable/2.10.2/dart-core/List/sort.html

**Comment by nitneuq33000** [comment]
Thank you for the help, I successed

**Comment by softmarshmallow** [comment]
Your welcome. closing.
