### ISSUE TITLE
Can we have null-safety support?

### ISSUE THREAD

**Issue by long1eu** [softmarshmallow/flutter-timeline#16]

**Comment by softmarshmallow** [comment]
Will do ! I've just updated [dynamic](https://github.com/bridgedxyz/dynamic) for flutter2, and this will have the support too.

**Comment by nitneuq33000** [comment]
Same, it's the last plugin I'm waiting to upgrade flutter ^^

**Comment by nitneuq33000** [comment]
Hello @long1eu just saw your fork with the null safety add, I don't know if it's finish, but if yes, it can be super helpful if a pullrequest is add or If @softmarshmallow no longer maintain this package, push to dart dev for the community. I'm a neeb, and don't know how to do this. it would take me months to get there

**Comment by softmarshmallow** [comment]
Try 0.3.0
