### ISSUE TITLE
Please add a null safety support

### ISSUE THREAD

**Issue by mohsinsheikhani** [softmarshmallow/flutter-timeline#19]

**Comment by softmarshmallow** [comment]
The current main branch has a null safety support. I'll publish it on pub later this week.
Until then, you can use git to load on pub. :)

**Comment by dev-horacebg** [comment]
Any news on this?

**Comment by softmarshmallow** [comment]
Working on this now.

**Comment by softmarshmallow** [comment]
Try 0.3.0
