### ISSUE TITLE
Possible to save events ? 

### ISSUE THREAD

**Issue by nitneuq33000** [softmarshmallow/flutter-timeline#4]
Hello and thank you for this package that I searched. I work great for me but I don't found how to use sharedpreference to save event and load when I init the app. Thank you

**Comment by softmarshmallow** [comment]
@nitneuq33000 hi.
the data management part is something "you" have to implement yourself.


here is some abstract code for it. (it wont comile, just for an example)


```dart

saveData(D d){}
D loadData(){}

builtTimeline(){
  return FutureBuilder<D>(
     builder: (c, s){
        return Timeline();
     },
     future: loadData
   );
}
```
